apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-portfolio
  labels:
    app: python-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-portfolio
  template:
    metadata:
      labels:
        app: python-portfolio
    spec:
      containers:
      - name: python-portfolio
        image: localhost:32000/moustapha-python:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-portfolio-service
spec:
  selector:
    app: python-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
  type: NodePort
